# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/Shopify/sarama"
  source = "github.com/Mongey/sarama"
  branch = "cm-v1-create-acl-request"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "v0.11.8"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/hashicorp/go-uuid"
  version = "1.0.0"
